default:
  tags:  
    - lab

stages:
 - smoke_test

cache:
  paths:
    - .m2/repository
    - target/

Smoke-Test:
  image: maven:3.8-jdk-11
  stage: smoke_test
  script:
    - echo "This job is for maven packaging"
    - mvn clean install
    



